---
title: " "
output: 
  html_document:
    toc_float: true
  
---




---
title: "GLHLTH 758: Case Studies in Data Science"
description: "Application of statistical and data science skills to in-depth data analysis projects in global health. Principled use and interpretation of modern tools, including data wrangling and munging, visualization, exploratory analysis, predictive modeling, and inference using modern statistical software applied to global health data. Emphasis on communication of analysis results both technically and non-technically via presentations and written reports. Students must have access to data for course project. Prerequisite: GLHLTH 705"
markup: "mmark"
---

#Welcome to Case Studies in Global Health!

### Class Meetings

<font color="#6CA0DC"><i class="fas fa-university fa-lg"></i></font> &nbsp; Trent 124 

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; WF 8:30-9:45am


### Professor

| [Professor Amy Herring](https://stat.duke.edu/people/amy-h-herring)  <a href="mailto:amy.herring@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp; 

Office hours Wednesday and Thursday 1:45-2:45 (or by appointment), 208 Old Chemistry Building

### Materials

You should have access to a laptop and bring it to every class, fully charged. Texts and readings will be assigned as needed. Required software packages include R/RStudio (free) and Tableau (free for students).


### Topics and Important Dates
GLHLTH 758 contains a mixture of lectures and hands-on data analysis by groups.

Note: this schedule is approximate and is likely to be modified as the course progresses. Assignments are due at the beginning of class unless otherwise specified.

|Date           |Topic                      |Deliverables     |
| ----------    | -----------------         | --------------- |
| August 28     | Welcome, Groups, and CS1: Healthy Babies      |       |
| August 30     | CS1: R and Data Visualization    |     RStudio Installed and Video Tutorial under R Basics Tab Completed, Bring Completed Getting to Know You Sheets (on Sakai) to Class            |
| September 4   | CS1: Hands on with R  | Proposals for Individual Case Studies & Group Expectations Documents Signed |
| September 6   | CS1: Data Wrangling and Visualization | |
| September 11  | CS1: Tableau for Data Visualization | |
| September 13  | CS1: Lab: Tableau | CS1 Topic and Plan |
| September 18  | CS2: Regression Modeling | |
| Septmeber 20  | CS2: Interaction in Regression | |
| September 25  | Group Presentations of CS1; Regression | CS1 Final Report|
| Septmeber 27  | Individual Project Proposal Presentations | Individual Project Statistical Analysis Plan |
| October 2     | Individual Project Proposal Presentations |   | 
| October 4     | Group Work on CS 2 | CS2 Interim Report |
| October 9    | CS2: Logistic Regression | |
| October 11    | CS2: Statistical Power |  |
| October 16    | CS2: Interaction in Logistic Regression |   |
| October 18    | CS2: Hands-on Logistic Regression | |
| October 23    | CS2: Small Sample Methods |   |
| October 25    | CS2 Presentations  |  CS2 Final Report | 
| October 30    | CS3: Longitudinal Data |   |
| November 1    | CS3: Hands-on Longitudinal Data | |
| November 6    | CS3: Longitudinal Data |  |
| November 8    | CS3 Presentations | CS3 Final Report |
| November 13   | Individual Case Study Presentations |   |
| November 15   | Individual Case Study Presentations |  |
| November 20 | Individual Case Study Presentations | |
| November 22 | Individual Case Study Presentations | Individual Case Studies |



