---
title: "Policies"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```




###Diversity & Inclusiveness:

The Duke University Community Commitment states: "Because diversity is essential to fulfilling the university’s mission, Duke is committed to building an inclusive and diverse university community.  Every student, faculty, and staff member —whatever their race, gender, age, ethnicity, cultural heritage or nationality; religious or political beliefs; sexual orientation or gender identity; or socioeconomic, veteran or ability status—has the right to inclusion, respect, agency and voice in the Duke community.  Further, all members of the University community have a responsibility to uphold these values and actively foster full participation in university life."

It is my goal for our learning environment to facilitate learning and intellectual development for everyone. To help accomplish this:
  
  - If you have a name and/or set of pronouns that differ from those that appear in your official Duke records, please let me know!
  - We are constantly learning more about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. 

### Academic integrity:

Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, respect, and accountability. Citizens of this community commit to reflect upon and uphold these principles in all academic and nonacademic endeavors, and to protect and promote a culture of integrity.

Remember the Duke Community Standard that you have agreed to abide by:
  
To uphold the Duke Community Standard:
  
- I will not lie, cheat, or steal in my academic endeavors;
- I will conduct myself honorably in all my endeavors; and
- I will act if the Standard is compromised.

Cheating or plagiarism on assignments, lying about an illness or absence and other forms of academic dishonesty are a breach of trust with classmates and faculty, violate the <a href="https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard">Duke Community Standard</a>, and will not be tolerated. Such incidences will result in a 0 grade.  Additionally, there may be penalties to your final class grade along with being reported to the Graduate School.

Please review the Academic Dishonesty policies <a href="https://studentaffairs.duke.edu/conduct/z-policies/academic-dishonesty">here</a>. 

- Several datasets we are privileged to use in class are confidential and cannot be distributed more broadly. Further dissemination of such datasets, made available on Sakai, will be considered a violation of the Duke Community Standard. If you are unsure whether you can use a dataset for purposes beyond class, please ask me.

- Most of the work assigned in class is collaborative. The individual case study must be completed independently. 

**Referencing code:** The web contains an enormous volume of code that you may find useful. You are welcome to make use of any online resources, but you must explicitly cite your sources. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. On the individual case study you may not directly share code with another student in this class, and on team assignments you may not share code with another team in this class (you are welcome to discuss the problems together and ask for advice, but you may not send or make use of code from another team). 

### Course components:

#### Class sessions:

If you miss class or would like to review the material covered in class, you can [view the recordings](https://trinity.capture.duke.edu/Panopto/Pages/Sessions/List.aspx?folderID=caf0593f-fe8e-4117-ae46-a94a00e0573c). Note that you will need to log in with your Net ID.

#### Teams:

On the first day of class, we will develop teams of around 4 students - these teams will stay consistent 
throughout the semester (barring extraordinary circumstances). You will work in these teams during 
class and on the group case studies. The process of forming teams will be completely transparent 
and based on self-reported data. Please follow the [Team Policies](grouppolicies.html) for group work.

#### Case Studies:

GLHLTH 758 involves detailed analysis of a series of case studies using current, relevant data. Each case study will involve a final submission and in some cases one or more interim submissions. Final case study submissions will involve a written report and may involve an oral presentation to be viewed by the other teams (in class or by video, as assigned). 

Additional details on the case studies will be provided as the course progresses.


Each individual case study will be graded based on written reports and an oral presentation. 

Each case study will have a page limit, and under no circumstances should font sizes less than 11 point be used, with the exception of labels in figures (and then only if they are still clearly legible to readers of all ages).




### Grading:

Your final grade will be comprised of the following:

|Component | % of Grade |
| ----------    | -----------------  |     
|Group case studies           | 60% |
|Individual case study        | 25% |
|Class participation     | 15% |

Class attendance is a firm expectation. Participation grades will reflect attendance and participation in shorter or in-class assignments.

Cumulative numerical averages of 90 - 100 are guaranteed at least an A-, 80 - 89 at least a B-, and 70 - 79 at least a C-; however, the exact ranges for letter grades will be determined at the end of the semester. The more evidence there is that the class is performing at the highest level, the higher the grade distribution will be.

Group case study submissions will be accompanied by teamwork evaluations, completed individually by team members. Groups are encouraged to hold members to high expectations for participation, and the instructor may become involved if one or more group members are not meeting group standards. Group case study grades may need to be adjusted to reflect unequal effort or contributions from team members.


### Excused Absences:

Students who miss a class due to a religious holiday or short-term illness should let me know as soon as possible. Note that these excused absences do not excuse you from assigned case studies; it is your responsibility to make alternative arrangements with your team to participate.

If you are faced with a personal or family emergency or a
chronic health condition that interferes with your ability to attend or
complete classes, please let me know right away, and we can make a plan.

### Late / missed work

Late work policy for case study reports: 

- late, but within 24 hours of due date/time: -20%
- any later: no credit

- Late work will not be accepted for the individual case study. 

- You must complete the individual case study and present it to the class in order to pass this course.

### Regrade requests

Regrade requests must be made within three days of when a report is returned. These will be honored if points were tallied incorrectly, or if you feel part of your report is correct, but it was marked wrong. No regrade will be made to alter the number of points deducted for an issue. There will be no grade changes after the individual project presentations.

### Professionalism

- Please refrain from texting or using your computer for anything other than coursework during class.


